logging:
  level:
    root: INFO

    # Your application logs
    com.pemc.crss: INFO

    # Connection pool (only WARN unless debugging pool issues)
    com.zaxxer.hikari: WARN

    # Hibernate – keep quiet
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: ERROR
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR


spring:
  datasource:
    url: jdbc:oracle:thin:@//192.168.41.33:1604/EMDBTST
    username: crss_tod
    password: crss_tod
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      pool-name: OracleHikariCP
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        show_sql: false
        format_sql: false

  redis:
    host: redis-master.iemop.svc.cluster.local
  security:
    oauth2:
      resource:
        token-info-uri: https://crss-dev.exist.com.ph/uaa/oauth/check_token
      client:
        client-id: crss
        client-secret: crsssecret

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          [
            'configprops',
            'env',
            'health',
            'info',
            'logfile',
            'loggers',
            'prometheus',
            'threaddump'
          ]
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}

authorization:
  server:
    user-info-uri: https://crss-dev.exist.com.ph/uaa/user


settlement:
  url: jdbc:postgresql://iemop-dev-db.postgres.database.azure.com:5432/settlement
  username: iemop
  password: "@oPL0YwPCql06WMN3YI3"

registration:
  url: jdbc:postgresql://iemop-dev-db.postgres.database.azure.com:5432/crss?currentSchema=registration
  username: iemop
  password: "@oPL0YwPCql06WMN3YI3"



rbcq:
  storage:
    upload-path: C:/Users/ISPD-IEMOP-CRSS/Desktop/sampleBCQPath
    processed-path: C:/Users/ISPD-IEMOP-CRSS/Desktop/sampleBCQPath/processed
    rejected-path: C:/Users/ISPD-IEMOP-CRSS/Desktop/sampleBCQPath/rejected

app:
  api-key: i3m0p


