logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate: DEBUG
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: TRACE

spring:
  application:
    name: rbcq
  datasource:
    url: jdbc:oracle:thin:@//192.168.94.161:1604/emdbtest
    username: crss_tod
    password: crss_tod
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      pool-name: OracleHikariCP
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        show_sql: true
        format_sql: true

  security:
    oauth2:
      resource:
        token-info-uri: https://crss-dev.exist.com.ph/uaa/oauth/check_token
      client:
        client-id: crss
        client-secret: crsssecret

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          [
            'configprops',
            'env',
            'health',
            'info',
            'logfile',
            'loggers',
            'prometheus',
            'threaddump'
          ]
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
  prometheus:
    metrics:
      export:
        enabled: true
        step: 60
  metrics:
    enable:
      http: true
      jvm: true
      logback: true
      process: true
      system: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0, 0.5, 0.75, 0.95, 0.99, 1.0
    tags:
      application: ${spring.application.name}

authorization:
  server:
    user-info-uri: https://crss-dev.exist.com.ph/uaa/user
